package app

type Action uint8

const (
	NoAction Action = iota
	SelectChat
	SelectNext
	SelectPrevious
	FocusPane
	FocusNext
	FocusPrevious
	Activate
	ToggleDetails
	Close
	PageUp
	PageDown
	ComposerBackspace
	ComposerNewline
	ComposerSubmit
	Retry
	Quit
	SelectMessage
	OpenMessageActionMenu
	CopyMessage
	ViewUserInfo
	SelectNextMessage
	SelectPreviousMessage
	ReplyMessage
	CancelReply
	EditMessage
	CancelEdit
	DeleteMessage
	DeleteForEveryone
	ForwardMessageSource
	PinMessage
	ReactMessage
	ViewMessageMedia
	OpenPhotoSend
	PhotoSendSubmit
	OpenStickerPicker
	StickerMoveLeft
	StickerMoveRight
	StickerMoveUp
	StickerMoveDown
	StickerActivate
	OpenMessageSearch
	SubmitMessageSearch
	OpenPinnedMessages
	SelectNextUnread
	SelectNextMention
	CommandMenuNext
	CommandMenuPrevious
	CommandMenuActivate
	CommandMenuDismiss
	OpenChatSearch
	SubmitChatSearch
	OpenMembers
	OpenInviteLinks
	OpenInviteLinkDetail
	CopyInviteLink
	CreateInviteLink
	RevokeInviteLink
	ConfirmRevokeInviteLink
	CancelRevokeInviteLink
	SelectMember
	OpenDetailsAvatar
	OpenMemberDetail
	CloseMemberDetail
	ViewMemberAvatar
	CopyMemberUsername
	AddMemberContact
	RemoveMemberContact
	BlockMember
	UnblockMember
	OpenTopics
	SelectTopic
	SelectAllMessages
	OpenChatActionMenu
	OpenChatFromMenu
	OpenGroupPermissions
	OpenChatSettings
	EditChatSetting
	SelectChatSlowMode
	SaveChatSetting
	OpenMemberAdministration
	ToggleAdministrationItem
	SaveAdministration
	SelectAdministrationAction
	ConfirmAdministrationAction
	CancelAdministrationAction
	ViewChatInfo
	MarkChatRead
	MarkChatUnread
	MuteChat
	UnmuteChat
	PinChat
	UnpinChat
	ArchiveChat
	UnarchiveChat
	ClearChatHistory
	DeleteConversation
	DeleteChat
	LeaveChat
	JoinChat
	ConfirmChatAction
	CancelChatAction
)
